----- TEMPLATE ------ INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES(?, now(), now(), ?, ?, false, '', '', '', '', '', '', 0);

---------------------
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES('e098f7c6-dac0-43ab-b3f9-a6bc2a707780'::uuid, '2024-01-11 18:33:08.548', '2024-01-11 18:33:08.548', '10000000-0000-0000-0000-000000000001'::uuid, '10000000-0000-0000-0000-000000000001'::uuid, true, 'f.tiralongo@gmail.com', 'Pippo', 'Mao', '', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'FT', 0);

INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES('e108f7c6-dac0-43ab-b3f9-a6bc2a707780'::uuid, now(), now(), '10000000-0000-0000-0000-000000000001'::uuid, '10000000-0000-0000-0000-000000000001'::uuid, true, 'admin@mail.com', 'root', 'root', 'Developer', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'ADMIN', 'ADMIN');

INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'ADMIN', 'ADMIN', true, 'ASmith@mail.com', 'Alice', 'Smith', 'Designer', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'ali', 'EDITOR');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator3', 'modifier3', true, 'user3@example.com', 'Bob', 'Johnson', 'Engineer', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'eva', 'EDITOR');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator4', 'modifier4', true, 'user4@example.com', 'Eva', 'Miller', 'Manager', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'eva', 'EDITOR');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator5', 'modifier5', true, 'user5@example.com', 'Mike', 'Williams', 'Analyst', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'mike', 'EDITOR');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator6', 'modifier6', true, 'user6@example.com', 'Sophie', 'Clark', 'Consultant', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'sophie', 'USER');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator7', 'modifier7', true, 'user7@example.com', 'Alex', 'Turner', 'Developer', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'alex', 'USER');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator8', 'modifier8', true, 'user8@example.com', 'Grace', 'Harrison', 'Designer', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'grace', 'USER');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator9', 'modifier9', true, 'user9@example.com', 'Daniel', 'Evans', 'Engineer', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'daniel', 'USER');
INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES ('?', now(), now(), 'creator10', 'modifier10', true, 'user10@example.com', 'Lily', 'Moore', 'Manager', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'lily', 'USER');



-----------


INSERT INTO "user" (id, "createdAt", "lastModifiedAt", "createdByUserId", "lastModifiedByUserId", active, email, "name", surname, profession, "passwordHash", "nickName", "role") VALUES('e098f7c6-dac0-43ab-b3f9-a6bc2a707780'::uuid, '2024-01-11 18:33:08.548', '2024-01-11 18:33:08.548', '10000000-0000-0000-0000-000000000001'::uuid, '10000000-0000-0000-0000-000000000001'::uuid, true, 'f.tiralongo@gmail.com', 'Pippo', 'Mao', '', '$2b$12$O752y0gODLDNPgSaV0kqJ.Qyc43PNDTqBTkx4jW0CJM/UPKGkUpP6', 'FT', 0);